---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 12
  
platforms:
  - name: ubuntu-12.04
    driver:
      box: express42/ubuntu12.04-chef11
  - name: ubuntu-14.04
    driver:
      box: express42/ubuntu-14.04

suites:
  - name: distro
    run_list:
      - recipe[rsyslog_test::distro]
  - name: v7
    run_list:
      - recipe[rsyslog_test::v7]  
  - name: v8
    run_list:
      - recipe[rsyslog_test::v8]